scripts/go: update the go version
During fuzzing, we keep observing the crash in the go runtime "fatal
error: s.allocCount != s.nelems && freeIndex == s.nelems".

It seems caused by a GO bug which is possibly disappeared [1]. With a
hope of fixing it, let's update the go version.

[1]: https://github.com/golang/go/issues/61726